### ISSUE TITLE
如何验证

### ISSUE THREAD

**Issue by Liujingxiu23** [YoungSeng/Speech-driven-expressions#1]
你好，非常感谢你的分享。对这个课题比较感兴趣，但不太了解，想请教下，假设训练了模型，如何验证呢？ 就是怎么生成一段驱动视频呢？是有什么开源工具吗。

**Comment by YoungSeng** [comment]
可以参考 5. Visualization，用blender生成一段驱动视频

**Comment by Liujingxiu23** [comment]
谢谢你的回复！
