### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by liushifu12138** [YoungSeng/Speech-driven-expressions#10]
Traceback (most recent call last):
  File "./scripts/synthesize.py", line 233, in <module>
    main(args.ckpt_path, args.transcript_path, args.wav_path)
  File "./scripts/synthesize.py", line 64, in main
    args, generator, loss_fn, speaker_model, out_dim = utils.train_utils.load_checkpoint_and_model(checkpoint_path, device)
  File "/home/xiaoduo/liu/Speech-driven-expressions-main/Tri/scripts/utils/train_utils.py", line 190, in load_checkpoint_and_model
    generator.load_state_dict(checkpoint['gen_dict'],strict=False)
  File "/home/xiaoduo/miniconda3/envs/3D/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PoseGenerator:
        size mismatch for audio_encoder.model.masked_spec_embed: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for audio_encoder.model.feature_projection.projection.weight: copying a param with shape torch.Size([1024, 512]) from checkpoint, the shape in current model is torch.Size([768, 512]).
        size mismatch for audio_encoder.model.feature_projection.projection.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for audio_encoder.model.encoder.pos_conv_embed.conv.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for audio_encoder.model.encoder.pos_conv_embed.conv.weight_v: copying a param with shape torch.Size([1024, 64, 128]) from checkpoint, the shape in current model is torch.Size([768, 48, 128]).

**Comment by YoungSeng** [comment]
维度不正确，当前模型是768维度的，保存的模型是1024的

**Comment by liushifu12138** [comment]
![111](https://github.com/YoungSeng/Speech-driven-expressions/assets/71754694/86c7b64f-6022-4c1f-8246-2c9a84bce596)
这是我的输出结果，请问正常么

**Comment by YoungSeng** [comment]
看起来比较正常，可以可视化一下看看结果

**Comment by liushifu12138** [comment]
请问需要修改fp么？在哪修改？谢谢你的项目

**Comment by YoungSeng** [comment]
你的意思是fps吗？fps在这儿修改：

https://github.com/YoungSeng/Speech-driven-expressions/blob/5e7c35aaf47f23bc183beec684af4ed95a5e1fd9/Tri/config/parse_args.py#L51

另外这儿也需要修改，https://github.com/YoungSeng/Speech-driven-expressions/blob/5e7c35aaf47f23bc183beec684af4ed95a5e1fd9/Tri/config/parse_args.py#L52

`n_poses`应该是2×`motion_resampling_framerate`+`n_seeds`, `n_seeds`是你自己设置的超参数，一般5左右感觉差不多了。

**Comment by liushifu12138** [comment]
OK
7876，2778300 这两个参数应该如何计算？我已经计算了get_pitch的长度，非常感谢您的项目！

**Comment by YoungSeng** [comment]
请参考这个[issue](https://github.com/YoungSeng/Speech-driven-expressions/issues/8#issuecomment-1539327371).

**Comment by liushifu12138** [comment]
OK，请问您的训练集音频大概有几个小时？

**Comment by YoungSeng** [comment]
大概四十多分钟吧好像

**Comment by liushifu12138** [comment]
感谢，OK了

**Comment by liushifu12138** [comment]
OK,感谢你的项目

**Comment by sxyddo35831** [comment]
我遇到了  https://github.com/YoungSeng/Speech-driven-expressions/issues/6#issuecomment-1571769063 一样的错误，然后我将https://github.com/YoungSeng/Speech-driven-expressions/blob/5e7c35aaf47f23bc183beec684af4ed95a5e1fd9/Tri/scripts/model/multimodal_context_net.py#L142 处取消注释来使shape为64而不是64+2的，并修改generator.load_state_dict(checkpoint['gen_dict'],strict=False)来使加载pretrain模型成功。，分享给大家。 然后想要在这个issue中看更多的信息，发现作者和提问者的对话显示不全。有任何人成功inference或者train了吗，可以回复我分享一下数据准备的流程和格式，任何回复都将是有帮助的，谢谢列位

**Comment by YoungSeng** [comment]
strict=False显然是不正确的，时间太久了我已经没有继续做这个方向了，整个模型都很简单，主要是提供一种思路，重点在于数据处理的pipeline，可能模型确实不对吧，不能公开数据集也确实难以复现

**Comment by sxyddo35831** [comment]
> strict=False显然是不正确的，时间太久了我已经没有继续做这个方向了，整个模型都很简单，主要是提供一种思路，重点在于数据处理的pipeline，可能模型确实不对吧，不能公开数据集也确实难以复现

事实确实如此。看到作者在代码中的数据处理，训练调试都留下了很多足迹，这些足迹能够让我们跟随着快速产出一个类似的技术。非常具有参考意义，但是这几天调试学习的过程中不管是Inference还是Train都遇到了非常多的问题，导致不能跑通一个最小流程，来理解代码中注释无法解释的部分。还是希望作者不管是Inference提供一个对的pretrained模型还是提供一条训练数据（一条就够了...哪怕数据是不准确的。也能把代码run起来）我们也可以参考着继续进行下去。
