### ISSUE TITLE
请问是否可以提供fbx模型可视化渲染

### ISSUE THREAD

**Issue by ForrestPi** [YoungSeng/Speech-driven-expressions#2]
你好，请问是否可以提供fbx模型供可视化渲染

**Comment by YoungSeng** [comment]
可以试试这儿的fbx模型，https://www.polywink.com/15-facial-animation-for-iphone-x.html

点击`DOWNLOAD A SAMPLE`

**Comment by ForrestPi** [comment]
Thanks
