### ISSUE TITLE
请求数据集

### ISSUE THREAD

**Issue by ZiqiaoPeng** [YoungSeng/Speech-driven-expressions#3]
你好，我最近在学习这方面的算法，但是我不太清楚这个数据集的输入是什么样的，请问是否可以分享一下输入的数据格式呢？

**Comment by YoungSeng** [comment]
语音：.wav文件，需要重采样到16000Hz
文本：.doc文件，每个文件包含几个音频的文本，我将其转化成了文本文件并做了强制对齐
表情：.csv文件，包含行（总帧数）x列（52个blendshape参数）

其实数据处理挺麻烦的，可以使用你自己的数据集，另外这两个你可以参考一下：

1. 这里有blendshape示例：

http://ailab.aiwin.org.cn/my/datasets/download/7400cca4-9990-41df-aa36-92011f6dd6ad

2. 这里有数据规模和内容覆盖：

http://ailab.aiwin.org.cn/competitions/69#learn_the_details-overview

**Comment by Mindusk** [comment]
好滴，谢谢你~请问音频处理之后的维度如何和Blendshape匹配呀，音频处理后维度应该是多少呢？我理解的是音频处理后的维度应该是一帧对应一小段音频，但是我不清楚应该音频输出的维度应该是多少。
