### ISSUE TITLE
代码训练时异常

### ISSUE THREAD

**Issue by Rookie-Kai** [YoungSeng/Speech-driven-expressions#5]
您好，非常感谢您的分享
但是我在尝试您的项目时
按要求说明要求处理好了数据后，运行train.py文件时，训练结果出现异常
loss值一直固定在0，我可以保证我的数据是正常的，但是不知道为何在训练时出现了这种问题

>  2023-02-02 15:36:26,276: Reading data '/mnt/vdh/Speech-driven-expressions-main/data/trn/lmdb/lmdb_train'...
> 2023-02-02 15:36:26,276: Found pre-loaded samples from /mnt/vdh/Speech-driven-expressions-main/data/trn/lmdb/lmdb_train_cache
> 2023-02-02 15:36:26,298: Reading data '/mnt/vdh/Speech-driven-expressions-main/data/val/lmdb/lmdb_test'...
> 2023-02-02 15:36:26,298: Found pre-loaded samples from /mnt/vdh/Speech-driven-expressions-main/data/val/lmdb/lmdb_test_cache
> 0 0
> Some weights of the model checkpoint at /mnt/vdh/Audio2Face/chinese-roberta-wwm-ext were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.bias']
> - This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> 1
> 2023-02-02 15:36:36,444: [VAL] loss: 0.000, joint mae: 0.000 / 0.3s
> 2023-02-02 15:36:36,445:   *** BEST VALIDATION LOSS: 0.000
> 2023-02-02 15:36:38,995: Saved the checkpoint
> 2023-02-02 15:36:39,542: [VAL] loss: 0.000, joint mae: 0.000 / 0.3s
> 2023-02-02 15:36:39,542:   best validation loss so far: 0.000 at EPOCH 0
> 2023-02-02 15:36:40,084: [VAL] loss: 0.000, joint mae: 0.000 / 0.3s
> 2023-02-02 15:36:40,084:   best validation loss so far: 0.000 at EPOCH 0
> 2023-02-02 15:36:40,615: [VAL] loss: 0.000, joint mae: 0.000 / 0.3s
> 2023-02-02 15:36:40,616:   best validation loss so far: 0.000 at EPOCH 0
> 2023-02-02 15:36:41,163: [VAL] loss: 0.000, joint mae: 0.000 / 0.3s
> 2023-02-02 15:36:41,164:   best validation loss so far: 0.000 at EPOCH 0
> 2023-02-02 15:36:41,726: [VAL] loss: 0.000, joint mae: 0.000 / 0.3s
> 2023-02-02 15:36:41,727:   best validation loss so far: 0.000 at EPOCH 0
> 2023-02-02 15:36:42,268: [VAL] loss: 0.000, joint mae: 0.000 / 0.3s
> 2023-02-02 15:36:42,268:   best validation loss so far: 0.000 at EPOCH 0
> 2023-02-02 15:36:42,829: [VAL] loss: 0.000, joint mae: 0.000 / 0.3s
> 2023-02-02 15:36:42,830:   best validation loss so far: 0.000 at EPOCH 0
> 2023-02-02 15:36:43,382: [VAL] loss: 0.000, joint mae: 0.000 / 0.3s
> 2023-02-02 15:36:43,382:   best validation loss so far: 0.000 at EPOCH 0
> 2023-02-02 15:36:43,903: [VAL] loss: 0.000, joint mae: 0.000 / 0.3s
> 2023-02-02 15:36:43,903:   best validation loss so far: 0.000 at EPOCH 0
> 2023-02-02 15:36:44,440: [VAL] loss: 0.000, joint mae: 0.000 / 0.3s
> 2023-02-02 15:36:44,441:   best validation loss so far: 0.000 at EPOCH 0
> 2023-02-02 15:36:47,256: Saved the checkpoint

请问您在训练时出现过类似问题么，您是如何处理并解决的呢？
再次感谢您的分享

**Comment by YoungSeng** [comment]
请确认数据处理正常，从你发的情况来看是lmdb文件处理有问题？数据集长度都是 0 0，你看看lmdb文件是多大，如果是8kb就是错了，数据集一般处理完应该是几M几G的大小

**Comment by Rookie-Kai** [comment]
我又重新处理了一下lmdb文件，训练集中，我的data.mdb文件大小为245mb，lock.mdb文件大小为8kb，验证集中，我的data.mdb大小为78.86mb，lock大小为8kb，且cache文件中，二者的大小均为8kb

**Comment by YoungSeng** [comment]
lmdb看起来没问题，cache大小不对，请删除所有的cache文件重新跑train.py？的代码，里面的processor会重新生成正确的lmdb，如果还不正确的话请自己改写processor函数

**Comment by Rookie-Kai** [comment]
我在尝试重新生成后，在第一次运行train.py后，发现提示

> Traceback (most recent call last):
>   File "train.py", line 357, in <module>
>     main()
>   File "train.py", line 330, in main
>     data_mean=args.data_mean, data_std=args.data_std)
>   File "/mnt/vdh/Speech-driven-expressions-main/Tri/scripts/data_loader/lmdb_data_loader.py", line 97, in __init__
>     data_sampler.run()
>   File "/mnt/vdh/Speech-driven-expressions-main/Tri/scripts/data_loader/data_preprocessor.py", line 39, in run
>     self._sample_from_clip(vid, clip)
>   File "/mnt/vdh/Speech-driven-expressions-main/Tri/scripts/data_loader/data_preprocessor.py", line 83, in _sample_from_clip
>     end_time=subdivision_end_time)
>   File "/mnt/vdh/Speech-driven-expressions-main/Tri/scripts/data_loader/data_preprocessor.py", line 137, in get_words_in_time_range
>     for word in word_list:
> TypeError: 'NoneType' object is not iterable

此时生成的cache文件就会出现异常，data和lock文件大小仅为8kb

**Comment by Rookie-Kai** [comment]
出现上述问题的原因是，aiwin_dataset_to_lmdb.py 文件中，make_lmdb_gesture_dataset() 方法内注释掉了word_processing部分，导致生成的words为空，取消注释即可正常运行

我看到您的处理方法中采用了混合trn和val的方法，如果方便的话，能麻烦您开源混合数据集这部分的代码么
非常感谢您百忙之中的回复

**Comment by Rookie-Kai** [comment]
很抱歉打扰您，我再修改后尝试运行时，提示出现下述问题，好像是数据对齐出现异常

> Traceback (most recent call last):
>   File "train.py", line 357, in <module>
>     main()
>   File "train.py", line 350, in main
>     train_epochs(args, train_loader, test_loader, pose_dim=pose_dim, speaker_model=train_dataset.speaker_model)
>   File "train.py", line 157, in train_epochs
>     for iter_idx, data in enumerate(train_data_loader, 0):
>   File "/mnt/vdh/img_generator/wcw_dev/tools/miniconda3/envs/Audio2Face/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
>     data = self._next_data()
>   File "/mnt/vdh/img_generator/wcw_dev/tools/miniconda3/envs/Audio2Face/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
>     return self._process_data(data)
>   File "/mnt/vdh/img_generator/wcw_dev/tools/miniconda3/envs/Audio2Face/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
>     data.reraise()
>   File "/mnt/vdh/img_generator/wcw_dev/tools/miniconda3/envs/Audio2Face/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
>     raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in DataLoader worker process 3.
> Original Traceback (most recent call last):
>   File "/mnt/vdh/img_generator/wcw_dev/tools/miniconda3/envs/Audio2Face/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/mnt/vdh/img_generator/wcw_dev/tools/miniconda3/envs/Audio2Face/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/mnt/vdh/Speech-driven-expressions-main/Tri/scripts/data_loader/lmdb_data_loader.py", line 51, in word_seq_collate_fn
>     audio = default_collate(audio)
>   File "/mnt/vdh/img_generator/wcw_dev/tools/miniconda3/envs/Audio2Face/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
>     return torch.stack(batch, 0, out=out)
> RuntimeError: stack expects each tensor to be equal size, but got [35200] at entry 0 and [33205] at entry 1

您在处理AIWIN的数据时，遇到过类似问题么？

**Comment by YoungSeng** [comment]
Q1：8KB就是错误生成了cache文件，processor函数需要自己检查一下问题或者重写，可以参考一下这个项目如果生成lmdb的https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation
Q2：因为比赛的时候训练集是word的形式，测试集是txt的形式，文本处理是不一样的，所以这部分可能需要修改，混合其实也比较简单，不需另外的代码，你可以像我这样根据比赛划分训练集和测试集，你也可以根据上面的这个项目一样，按照8比1比1这种划分训练集和数据集
q3：这可能是因为我处理数据是按两秒钟生成的，然后有0.2秒钟的种子数据，这就是2.2秒钟，对应的16000赫兹就是35200；你这个问题可能是本身数据没有对齐，可以尝试循环的时候把零到最后一个I改成零到最后一个i- 1，即把最后一段的数据给拆掉

**Comment by YoungSeng** [comment]
我建议甚至可以不需要先划分训练和测试集，先把代码跑起来，再考虑如何划分数据集。
这个数据处理的代码是在这个共与手势生成的代码基础上改的，你可以看看他之前历史的分支，处理GENEA 2020 trinity数据集生成lmdb的代码

**Comment by Rookie-Kai** [comment]
很抱歉再次打扰您，我找了很久，也无法找到该去哪解决您说的数据对齐问题，请问我该去哪个文件进行修改呢？我使用的也是这次的数据集

**Comment by YoungSeng** [comment]
可能是最后一个位置不齐

尝试修改：

https://github.com/YoungSeng/Speech-driven-expressions/blob/5e7c35aaf47f23bc183beec684af4ed95a5e1fd9/Tri/scripts/data_loader/data_preprocessor.py#L74

为：

`for i in range(num_subdivision-1):`
