### ISSUE TITLE
data preprocess

### ISSUE THREAD

**Issue by Sander-houqi** [YoungSeng/Speech-driven-expressions#8]
数据预处理 tsv 文本可以给个例子？
原始语音如何转tsv？

感谢！

**Comment by YoungSeng** [comment]
训练集的文本如下word文档所示：
![image](https://user-images.githubusercontent.com/37477030/233294648-ab253b6e-1739-44b4-a3e3-230cda164cff.png)

tsv文本处理过程，首先用：
https://github.com/YoungSeng/Speech-driven-expressions/blob/5e7c35aaf47f23bc183beec684af4ed95a5e1fd9/data_process/process.py#L77
提取文本，然后用mfa进行对齐：
https://github.com/YoungSeng/Speech-driven-expressions/blob/5e7c35aaf47f23bc183beec684af4ed95a5e1fd9/data_process/process.py#L108
最后处理成tsv格式的文件，当然txt等格式也是可以的
https://github.com/YoungSeng/Speech-driven-expressions/blob/5e7c35aaf47f23bc183beec684af4ed95a5e1fd9/data_process/process.py#L113

最终得到的tsv，包括起始时间、结束时间和字：
![image](https://user-images.githubusercontent.com/37477030/233295555-d58de03f-f94d-41a8-9f4b-1d256d930a0f.png)

语音转文本可以用ASR模型，这里AIWIN的比赛提供了文本的

**Comment by Sander-houqi** [comment]
感谢及时回复，很清楚~

**Comment by Sander-houqi** [comment]
![image](https://user-images.githubusercontent.com/20236749/236984600-1d0f3034-56b9-438e-902c-096b139fbe71.png)
hi，这里的7876 ，2778300 是根据什么算出来的，如果我要用自有数据，数据对齐有什么要注意的么，比如n_poses, skeleton_resampling_fps 参数的设置？ 感谢~

**Comment by Sander-houqi** [comment]
![image](https://user-images.githubusercontent.com/20236749/236984600-1d0f3034-56b9-438e-902c-096b139fbe71.png)
hi，这里的7876 ，2778300 是根据什么算出来的，如果我要用自有数据，数据对齐有什么要注意的么，比如n_poses, skeleton_resampling_fps 参数的设置？ 感谢~

**Comment by YoungSeng** [comment]
就是这里需要对齐，举个列子，一段语音的wav长度是16000，音高是300，那么wav取8000时音高就应该取150，就是一个最基本的比例关系，需要根据你的滑窗决定模态切割的长度。你可以计算自己的resample系数如[here](https://github.com/youngwoo-yoon/Co-Speech_Gesture_Generation/blob/46671fc6af8a3dbcb93cdafca4f07bc064a2c3b1/scripts/data_loader/data_preprocessor.py#LL67C66-L67C66)

**Comment by Sander-houqi** [comment]
我理解总共是2.2s的数据，所以如果我fps 30的情况下，n_poses就应该是30*2.2, 对应的总长度就是35200，这样音频的滑动窗口就可以确定；但是pitch 和 volume 这两个采样的长度，我需要根据什么来改变，7876，2778300是提供的音频的2.2s对应的音高和总音高么，我应该怎么获得这两个对应的值？

**Comment by YoungSeng** [comment]
建议把35200长度的音频丢到`My/scripts/energy.py`中，测试一下`get_pitch`的长度，不是要7876或者2778300，这就是一个比例系数。
